import { notFound } from "next/navigation";
import { readPendingPlan } from "@/lib/import";
import { ImportReview } from "@/components/import-review";
import { ProcessingPoller } from "@/components/processing-poller";

export const dynamic = "force-dynamic";

type PageProps = {
  params: Promise<{ id: string }>;
};

export default async function ImportPlanPage({ params }: PageProps) {
  const { id } = await params;
  const plan = await readPendingPlan(id);
  if (!plan) notFound();

  // Plan still being generated by the LLM — show a friendly waiting state
  // and poll every 5s until planStatus flips to "ready" or "failed".
  if (plan.planStatus === "generating") {
    return (
      <div style={{ padding: "48px 56px", maxWidth: 720, margin: "0 auto" }}>
        <ProcessingPoller intervalMs={5000} />
        <h1 className="serif" style={{ fontSize: 24, fontWeight: 400 }}>
          {plan.title}
        </h1>
        <p style={{ marginTop: 12, color: "var(--ink-2)", fontSize: 14 }}>
          Rufino está generando el plan con Claude. Va a tardar 1–3 minutos.
          Podés cerrar esta pestaña y volver más tarde — la página va a
          actualizarse sola cuando el plan esté listo.
        </p>
        <div
          style={{
            marginTop: 24,
            padding: "16px 20px",
            border: "1px solid var(--hair)",
            borderRadius: 6,
            background: "var(--surface)",
            display: "flex",
            alignItems: "center",
            gap: 12,
          }}
        >
          <span
            aria-hidden
            style={{
              width: 8,
              height: 8,
              borderRadius: "50%",
              background: "var(--accent)",
              animation: "rufino-pulse 1.2s ease-in-out infinite",
              flexShrink: 0,
            }}
          />
          <span style={{ fontSize: 13, color: "var(--ink-2)" }}>
            Generando plan… ({plan.create.length} crear / {plan.update.length} updatear / {plan.triples.length} conexiones · heurístico)
          </span>
          <style>{`
            @keyframes rufino-pulse {
              0%, 100% { opacity: 0.4; }
              50% { opacity: 1; }
            }
          `}</style>
        </div>
        <details style={{ marginTop: 24, fontSize: 13, color: "var(--ink-3)" }}>
          <summary style={{ cursor: "pointer" }}>
            Ver el plan heurístico mientras se genera el real
          </summary>
          <div style={{ marginTop: 12 }}>
            <ImportReview plan={plan} />
          </div>
        </details>
      </div>
    );
  }

  if (plan.planStatus === "failed") {
    return (
      <div style={{ padding: "48px 56px", maxWidth: 720, margin: "0 auto" }}>
        <h1 className="serif" style={{ fontSize: 24, fontWeight: 400 }}>
          {plan.title}
        </h1>
        <div
          style={{
            marginTop: 16,
            padding: "12px 16px",
            border: "1px solid var(--red, #c2410c)",
            borderRadius: 6,
            background: "var(--surface-2)",
            color: "var(--red, #c2410c)",
            fontSize: 13,
          }}
        >
          La generación del plan falló: {plan.error || "error desconocido"}.
          Mostrando el plan heurístico como fallback — podés aplicar igual.
        </div>
        <div style={{ marginTop: 16 }}>
          <ImportReview plan={plan} />
        </div>
      </div>
    );
  }

  return <ImportReview plan={plan} />;
}
